// lib/repositories/food_emoji_repository.dart

class EmojiParser {
  static const Map<String, String> _emojiMap = {
    ':apple:': '🍎',
    ':banana:': '🍌',
    ':cherries:': '🍒',
    ':grapes:': '🍇',
    ':watermelon:': '🍉',
    ':strawberry:': '🍓',
    ':lemon:': '🍋',
    ':peach:': '🍑',
    ':pineapple:': '🍍',
    ':mango:': '🥭',
    ':avocado:': '🥑',
    ':broccoli:': '🥦',
    ':carrot:': '🥕',
    ':corn:': '🌽',
    ':cucumber:': '🥒',
    ':tomato:': '🍅',
    ':potato:': '🥔',
    ':chickpea:': '🧆',
    ':bread:': '🍞',
    ':croissant:': '🥐',
    ':bagel:': '🥯',
    ':pancakes:': '🥞',
    ':cheese:': '🧀',
    ':egg:': '🥚',
    ':fried_egg:': '🍳',
    ':bacon:': '🥓',
    ':hamburger:': '🍔',
    ':pizza:': '🍕',
    ':hotdog:': '🌭',
    ':fries:': '🍟',
    ':taco:': '🌮',
    ':burrito:': '🌯',
    ':spaghetti:': '🍝',
    ':sushi:': '🍣',
    ':ice_cream:': '🍨',
    ':cake:': '🎂',
    ':chocolate:': '🍫',
    ':cookie:': '🍪',
    ':coffee:': '☕',
    ':tea:': '🍵',
    ':milk:': '🥛',
    ':beer:': '🍺',
    ':wine:': '🍷',
    ':champagne:': '🍾',
    ':cocktail:': '🍸',
    ':tropical_drink:': '🍹',
    ':bubble_tea:': '🧋',
  };
  String getEmoji(String shortcode) => _emojiMap[shortcode] ?? '❓';
  bool hasEmoji(String shortcode) => _emojiMap.containsKey(shortcode);
}
