// plugins {
//     id 'com.android.application' version '8.8.0' apply false

// }

allprojects {
    // repositories {
    //     google()
    //     maven{url "https://storage.googleapis.com/download.flutter.io"}
    //     mavenCentral()
    //     gradlePluginPortal()
    // }
}



rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

