enum Activity {
  strength,
  cardio,
  hiit,
  activeRest;
}

Activity getActivity(int activityId) {
  return data.entries.firstWhere(
    (element) => element.key == activityId,
    orElse: () {
      return data.entries.elementAt(1);
    },
  ).value;
}

Map<int, Activity> data = {
  -1: Activity.hiit, //Check this too.
  0: Activity.cardio,
  1: Activity.cardio,
  16: Activity.cardio,
  17: Activity.cardio,
  18: Activity.cardio,
  19: Activity.cardio,
  20: Activity.cardio,
  21: Activity.cardio,
  22: Activity.cardio,
  24: Activity.cardio,
  25: Activity.cardio,
  27: Activity.cardio,
  28: Activity.cardio,
  29: Activity.cardio,
  30: Activity.cardio,
  31: Activity.cardio,
  32: Activity.cardio,
  33: Activity.cardio,
  34: Activity.cardio,
  35: Activity.hiit,
  36: Activity.cardio,
  37: Activity.cardio,
  38: Activity.hiit,
  39: Activity.hiit,
  42: Activity.cardio,
  43: Activity.activeRest,
  44: Activity.activeRest,
  45: Activity.strength,
  47: Activity.hiit, //CHECK!
  48: Activity.hiit,
  49: Activity.cardio,
  51: Activity.strength,
  52: Activity.hiit,
  53: Activity.hiit,
  55: Activity.hiit,
  56: Activity.hiit,
  57: Activity.cardio,
  59: Activity.strength,
  60: Activity.hiit,
  61: Activity.cardio,
  62: Activity.cardio,
  63: Activity.cardio,
  64: Activity.cardio,
  65: Activity.cardio,
  66: Activity.cardio,
  70: Activity.activeRest,
  71: Activity.cardio,
  73: Activity.cardio,
  74: Activity.cardio,
  75: Activity.cardio,
  76: Activity.cardio,
  77: Activity.cardio,
  82: Activity.cardio,
  83: Activity.strength,
  84: Activity.cardio,
  85: Activity.cardio,
  86: Activity.cardio,
  87: Activity.activeRest,
  88: Activity.activeRest,
  89: Activity.cardio,
  90: Activity.activeRest,
  91: Activity.cardio,
  92: Activity.cardio,
  93: Activity.cardio,
  94: Activity.hiit,
  95: Activity.cardio,
  96: Activity.hiit,
  97: Activity.cardio,
  98: Activity.hiit,
  99: Activity.strength,
  100: Activity.cardio,
  101: Activity.cardio,
  102: Activity.cardio,
  103: Activity.hiit,
  104: Activity.cardio,
  105: Activity.strength,
  106: Activity.cardio,
  107: Activity.strength,
  108: Activity.activeRest,
  109: Activity.activeRest, //Check!
  110: Activity.hiit,
  111: Activity.cardio,
  112: Activity.strength,
  113: Activity.strength,
  121: Activity.activeRest,
  123: Activity.strength,
  125: Activity.activeRest,
  126: Activity.cardio,
  127: Activity.hiit,
  128: Activity.activeRest,
  230: Activity.cardio,
  231: Activity.cardio,
  232: Activity.cardio,
  233: Activity.activeRest,
  234: Activity.cardio,
  235: Activity.strength,
  236: Activity.activeRest,
  237: Activity.activeRest,
  238: Activity.cardio,
  239: Activity.cardio,
  240: Activity.cardio,
};
